{
  "version": 2,
  "builds": [
    { "src": "public/index.html", "use": "@vercel/static" },
    { "src": "public/admin.html", "use": "@vercel/static" },
    { "src": "api/health.js", "use": "@vercel/node" },
    { "src": "api/auth/signin.js", "use": "@vercel/node" },
    { "src": "api/auth/signup.js", "use": "@vercel/node" },
    { "src": "api/auth/me.js", "use": "@vercel/node" },
    { "src": "api/auth/logout.js", "use": "@vercel/node" },
    { "src": "api/auth/google.js", "use": "@vercel/node" },
    { "src": "api/blog/index.js", "use": "@vercel/node" },
    { "src": "api/blog/[slug].js", "use": "@vercel/node" },
    { "src": "api/trades/index.js", "use": "@vercel/node" },
    { "src": "api/trades/[id].js", "use": "@vercel/node" },
    { "src": "api/user/profile.js", "use": "@vercel/node" },
    { "src": "api/config/index.js", "use": "@vercel/node" },
    { "src": "api/flags/index.js", "use": "@vercel/node" },
    { "src": "api/announcements/index.js", "use": "@vercel/node" },
    { "src": "api/admin/users.js", "use": "@vercel/node" }
  ],
  "routes": [
    { "src": "/api/health", "dest": "api/health.js" },
    { "src": "/api/auth/signin", "dest": "api/auth/signin.js" },
    { "src": "/api/auth/signup", "dest": "api/auth/signup.js" },
    { "src": "/api/auth/me", "dest": "api/auth/me.js" },
    { "src": "/api/auth/logout", "dest": "api/auth/logout.js" },
    { "src": "/api/auth/google", "dest": "api/auth/google.js" },
    { "src": "/api/blog/(.+)", "dest": "api/blog/[slug].js" },
    { "src": "/api/blog", "dest": "api/blog/index.js" },
    { "src": "/api/trades/(.+)", "dest": "api/trades/[id].js" },
    { "src": "/api/trades", "dest": "api/trades/index.js" },
    { "src": "/api/user/profile", "dest": "api/user/profile.js" },
    { "src": "/api/config", "dest": "api/config/index.js" },
    { "src": "/api/flags", "dest": "api/flags/index.js" },
    { "src": "/api/announcements", "dest": "api/announcements/index.js" },
    { "src": "/api/admin/users", "dest": "api/admin/users.js" },
    { "src": "/admin", "dest": "public/admin.html" },
    { "src": "/admin.html", "dest": "public/admin.html" },
    { "src": "/(.*)", "dest": "public/index.html" }
  ]
}
